package dataprojectreal;
public class DataProjectReal {
    public static void main(String[] args) {
        //BESIKTAS
        Player rafaSilva=new Player("Rafa Silva",1,"Right-wing",0);
        Player immobile=new Player("Immobile",2,"Striker",0);
        Player mertGunok=new Player("Mert Gunok",3,"GoalKeeper",0);
        Player gedson=new Player("Gedson",4,"Midfield",0);
        Player svensson=new Player("Svensson",5,"Defender",0);
        Player onurBulut=new Player("OnurBulut",6,"Defender",0);
        Player ndour=new Player("Ndour",7,"Midfield",0);
        PlayerList besiktas_playerList=new PlayerList();
        besiktas_playerList.addPlayerToList(rafaSilva);
        besiktas_playerList.addPlayerToList(immobile);
        besiktas_playerList.addPlayerToList(mertGunok);
        besiktas_playerList.addPlayerToList(gedson);
        besiktas_playerList.addPlayerToList(svensson);
        besiktas_playerList.addPlayerToList(onurBulut);
        besiktas_playerList.addPlayerToList(ndour);
        Team besiktas = new Team("Besiktas",1,0,0,besiktas_playerList,0);
        
        //GALATASARAY
        Player icardi=new Player("Icardi",8,"Striker",0);
        Player oshimen=new Player("Oshimen",9,"Striker",0);
        Player muslera=new Player("Muslera",10,"GoalKeeper",0);
        Player mertens=new Player("Mertens",11,"Midfield",0);
        Player abdulkerim=new Player("Abdulkerim",12,"Defender",0);
        Player sanchez=new Player("Sanchez",13,"Defender",0);
        Player torreira=new Player("Torreira",14,"Midfield",0);
        PlayerList galatasaray_playerList=new PlayerList();
        galatasaray_playerList.addPlayerToList(muslera);
        galatasaray_playerList.addPlayerToList(mertens);
        galatasaray_playerList.addPlayerToList(icardi);
        galatasaray_playerList.addPlayerToList(oshimen);
        galatasaray_playerList.addPlayerToList(abdulkerim);
        galatasaray_playerList.addPlayerToList(sanchez);
        galatasaray_playerList.addPlayerToList(torreira);
        Team galatasaray=new Team("Galatasaray",2,0,0,galatasaray_playerList,0);
        //FENERBAHCE
        Player cenkTosun=new Player("Cenk Tosun",15,"Striker",0);
        Player dzeko=new Player("Dzeko",16,"Striker",0);
        Player livakovic=new Player("Livakovic",17,"GoalKeeper",0);
        Player fred=new Player("Fred",18,"Midfield",0);
        Player becao=new Player("Becao",19,"Defender",0);
        Player djiku=new Player("Djiku",20,"Defender",0);
        Player tadic=new Player("Tadic",21,"Midfield",0);
        PlayerList fenerbahce_playerList=new PlayerList();
        Team fenerbahce=new Team("Fenerbahce",3,0,0,fenerbahce_playerList,0);
        //TRABZONSPOR
        Player banza=new Player("Banza",22,"Striker",0);
        Player visca=new Player("Visca",23,"Striker",0);
        Player ugurcan=new Player("Ugurcan",24,"GoalKeeper",0);
        Player ozanTufan=new Player("Ozan Tufan",25,"Midfield",0);
        Player savic=new Player("Savic",26,"Defender",0);
        Player batagor=new Player("Batagor",27,"Defender",0);
        Player okay=new Player("Okay",28,"Midfield",0);
        PlayerList trabzonspor_playerList=new PlayerList();
        trabzonspor_playerList.addPlayerToList(banza);
        trabzonspor_playerList.addPlayerToList(visca);
        trabzonspor_playerList.addPlayerToList(ugurcan);
        trabzonspor_playerList.addPlayerToList(ozanTufan);
        trabzonspor_playerList.addPlayerToList(savic);
        trabzonspor_playerList.addPlayerToList(batagor);
        trabzonspor_playerList.addPlayerToList(okay);
        Team trabzonspor=new Team("Trabzonpor",4,0,0,trabzonspor_playerList,0);
        //SIVASSPOR
        Player manaj=new Player("Manaj",29,"Striker",0);
        Player koita=new Player("Koita",30,"Striker",0);
        Player nikolic=new Player("Nikolic",31,"GoalKeeper",0);
        Player emrah=new Player("Emrah",32,"Midfield",0);
        Player ziyaErdal=new Player("Ziya Erdal",33,"Defender",0);
        Player camara=new Player("Camara",34,"Defender",0);
        Player azizbek=new Player("Azizbek",35,"Midfield",0);
        PlayerList sivasspor_playerList=new PlayerList();
        sivasspor_playerList.addPlayerToList(manaj);
        sivasspor_playerList.addPlayerToList(koita);
        sivasspor_playerList.addPlayerToList(nikolic);
        sivasspor_playerList.addPlayerToList(emrah);
        sivasspor_playerList.addPlayerToList(ziyaErdal);
        sivasspor_playerList.addPlayerToList(camara);
        sivasspor_playerList.addPlayerToList(azizbek);
        Team sivasspor=new Team("Sivasspor",5,0,0,sivasspor_playerList,0);
        //BASAKSEHIR
        Player pereira=new Player("Pereira",36,"Striker",0);
        Player keny=new Player("Keny",37,"Striker",0);
        Player volkanBabacan=new Player("Volkan Babacan",38,"GoalKeeper",0);
        Player pelkas=new Player("Pelkas",39,"Midfield",0);
        Player denizTuruc=new Player("Deniz Turuc",40,"Defender",0);
        Player onur=new Player("Onur",41,"Defender",0);
        Player kemen=new Player("Kemen",42,"Midfield",0);
        PlayerList basaksehir_playerList=new PlayerList();
        basaksehir_playerList.addPlayerToList(pereira);
        basaksehir_playerList.addPlayerToList(keny);
        basaksehir_playerList.addPlayerToList(volkanBabacan);
        basaksehir_playerList.addPlayerToList(pelkas);
        basaksehir_playerList.addPlayerToList(denizTuruc);
        basaksehir_playerList.addPlayerToList(onur);
        basaksehir_playerList.addPlayerToList(kemen);
        Team basaksehir=new Team("Basaksehir",6,0,0,basaksehir_playerList,0);
        //EYUPSOR
        Player emreMor=new Player("Emre Mor",43,"Striker",0);
        Player sinan=new Player("Sinan Gumus",44,"Striker",0);
        Player berkeOzer=new Player("Berke Ozer",45,"GoalKeeper",0);
        Player emreAkbaba=new Player("Emre Akbaba",46,"Midfield",0);
        Player tayfur=new Player("Tayfur Bingol",47,"Defender",0);
        Player caner=new Player("Caner Erkin",48,"Defender",0);
        Player dorukhan=new Player("Dorukhan Toköz",49,"Midfield",0);
        PlayerList eyupspor_playerList=new PlayerList();
        eyupspor_playerList.addPlayerToList(emreMor);
        eyupspor_playerList.addPlayerToList(sinan);
        eyupspor_playerList.addPlayerToList(berkeOzer);
        eyupspor_playerList.addPlayerToList(emreAkbaba);
        eyupspor_playerList.addPlayerToList(tayfur);
        eyupspor_playerList.addPlayerToList(caner);
        eyupspor_playerList.addPlayerToList(dorukhan);
        Team eyupspor=new Team("Eyupspor",7,0,0,eyupspor_playerList,0);
        //Example of print player and team
        tayfur.print(); System.out.println(" "); eyupspor.printTeam();
        //Players and teams are in hash table. 
        System.out.println(" ");
        HashTablePlayer htp = new HashTablePlayer(49);
        htp.putLinear(rafaSilva);
        htp.putLinear(immobile);
        htp.putLinear(mertGunok);
        htp.putLinear(gedson);
        htp.putLinear(svensson);
        htp.putLinear(onurBulut);
        htp.putLinear(ndour);
        htp.putLinear(icardi);
        htp.putLinear(oshimen);
        htp.putLinear(muslera);
        htp.putLinear(mertens);
        htp.putLinear(abdulkerim);
        htp.putLinear(sanchez);
        htp.putLinear(torreira);
        htp.putLinear(cenkTosun);
        htp.putLinear(dzeko);
        htp.putLinear(livakovic);
        htp.putLinear(fred);
        htp.putLinear(becao);
        htp.putLinear(djiku);
        htp.putLinear(tadic);
        htp.putLinear(banza);
        htp.putLinear(visca);
        htp.putLinear(ugurcan);
        htp.putLinear(ozanTufan);
        htp.putLinear(savic);
        htp.putLinear(batagor);
        htp.putLinear(okay);
        htp.putLinear(manaj);
        htp.putLinear(koita);
        htp.putLinear(nikolic);
        htp.putLinear(emrah);
        htp.putLinear(ziyaErdal);
        htp.putLinear(camara);
        htp.putLinear(azizbek);
        htp.putLinear(pereira);
        htp.putLinear(keny);
        htp.putLinear(volkanBabacan);
        htp.putLinear(pelkas);
        htp.putLinear(denizTuruc);
        htp.putLinear(onur);
        htp.putLinear(kemen);
        htp.putLinear(emreMor);
        htp.putLinear(sinan);
        htp.putLinear(berkeOzer);
        htp.putLinear(emreAkbaba);
        htp.putLinear(tayfur);
        htp.putLinear(caner);
        htp.putLinear(dorukhan);
        HashTableTeam htt = new HashTableTeam(7);
        htt.putLinear(besiktas);
        htt.putLinear(galatasaray);
        htt.putLinear(fenerbahce);
        htt.putLinear(trabzonspor);
        htt.putLinear(basaksehir);
        htt.putLinear(eyupspor);
        htt.putLinear(sivasspor);
        //Show both of them.
        htp.display(); System.out.println(" "); htt.display();
        //Players and teams in binary search tree.
        Search sp = new Search();
        sp.insertPlayer(rafaSilva.playerName);
        sp.insertPlayer(immobile.playerName);
        sp.insertPlayer(mertGunok.playerName);
        sp.insertPlayer(gedson.playerName);
        sp.insertPlayer(svensson.playerName);
        sp.insertPlayer(onurBulut.playerName);
        sp.insertPlayer(ndour.playerName);
        sp.insertPlayer(icardi.playerName);
        sp.insertPlayer(oshimen.playerName);
        sp.insertPlayer(muslera.playerName);
        sp.insertPlayer(mertens.playerName);
        sp.insertPlayer(abdulkerim.playerName);
        sp.insertPlayer(sanchez.playerName);
        sp.insertPlayer(torreira.playerName);
        sp.insertPlayer(cenkTosun.playerName);
        sp.insertPlayer(dzeko.playerName);
        sp.insertPlayer(livakovic.playerName);
        sp.insertPlayer(fred.playerName);
        sp.insertPlayer(becao.playerName);
        sp.insertPlayer(djiku.playerName);
        sp.insertPlayer(tadic.playerName);
        sp.insertPlayer(banza.playerName);
        sp.insertPlayer(visca.playerName);
        sp.insertPlayer(ugurcan.playerName);
        sp.insertPlayer(ozanTufan.playerName);
        sp.insertPlayer(savic.playerName);
        sp.insertPlayer(batagor.playerName);
        sp.insertPlayer(okay.playerName);
        sp.insertPlayer(manaj.playerName);
        sp.insertPlayer(koita.playerName);
        sp.insertPlayer(nikolic.playerName);
        sp.insertPlayer(emrah.playerName);
        sp.insertPlayer(ziyaErdal.playerName);
        sp.insertPlayer(camara.playerName);
        sp.insertPlayer(azizbek.playerName);
        sp.insertPlayer(pereira.playerName);
        sp.insertPlayer(keny.playerName);
        sp.insertPlayer(volkanBabacan.playerName);
        sp.insertPlayer(pelkas.playerName);
        sp.insertPlayer(denizTuruc.playerName);
        sp.insertPlayer(onur.playerName);
        sp.insertPlayer(kemen.playerName);
        sp.insertPlayer(emreMor.playerName);
        sp.insertPlayer(sinan.playerName);
        sp.insertPlayer(berkeOzer.playerName);
        sp.insertPlayer(emreAkbaba.playerName);
        sp.insertPlayer(tayfur.playerName);
        sp.insertPlayer(caner.playerName);
        sp.insertPlayer(dorukhan.playerName);
        Search st = new Search();
        st.insertTeam(besiktas.teamName);
        st.insertTeam(galatasaray.teamName);
        st.insertTeam(fenerbahce.teamName);
        st.insertTeam(sivasspor.teamName);
        st.insertTeam(trabzonspor.teamName);
        st.insertTeam(eyupspor.teamName);
        st.insertTeam(basaksehir.teamName);
        //Show players and teams in binary search tree.
        System.out.println(" ");
        System.out.println("Players : ");
        sp.printPlayers(); System.out.println(" ");
        System.out.println("Teams : ");
        st.printTeams();
        //Find a player and team in binary search tree.(We are searching icardi and galatasaray.)
        System.out.println(" ");
        System.out.println("Eyupspor and Tayfur are being searching.");
        sp.findPlayer(tayfur.playerName); st.findTeam(eyupspor.teamName);
        System.out.println(" ");
        //Match process.
        MatchProcess matchP = new MatchProcess(7);
        matchP.push(fenerbahce.teamName);
        matchP.push(besiktas.teamName);
        matchP.push(galatasaray.teamName);
        matchP.push(sivasspor.teamName);
        matchP.push(eyupspor.teamName);
        matchP.push(trabzonspor.teamName);
        matchP.push(basaksehir.teamName);
        //Match simulator.(Output will be in results.)
        MatchSim match1 = new MatchSim(galatasaray, besiktas);
        match1.simulator();
        MatchSim match2 = new MatchSim(besiktas, galatasaray);
        match2.simulator();
        MatchSim match3 = new MatchSim(galatasaray, fenerbahce);
        match3.simulator();
        MatchSim match4 = new MatchSim(fenerbahce, galatasaray);
        match4.simulator();
        MatchSim match5 = new MatchSim(galatasaray, sivasspor);
        match5.simulator();
        MatchSim match6 = new MatchSim(sivasspor, galatasaray);
        match6.simulator();
        MatchSim match7 = new MatchSim(galatasaray, eyupspor);
        match7.simulator();
        MatchSim match8 = new MatchSim(eyupspor, galatasaray);
        match8.simulator();
        MatchSim match9 = new MatchSim(galatasaray, trabzonspor);
        match9.simulator();
        MatchSim match10 = new MatchSim(trabzonspor, galatasaray);
        match10.simulator();
        MatchSim match11 = new MatchSim(galatasaray, basaksehir);
        match11.simulator();
        MatchSim match12 = new MatchSim(basaksehir, galatasaray);
        match12.simulator();
        MatchSim match13 = new MatchSim(besiktas, fenerbahce);
        match13.simulator();
        MatchSim match14 = new MatchSim(fenerbahce, besiktas);
        match14.simulator();
        MatchSim match15 = new MatchSim(besiktas, sivasspor);
        match15.simulator();
        MatchSim match16 = new MatchSim(sivasspor, besiktas);
        match16.simulator();
        MatchSim match17 = new MatchSim(besiktas, eyupspor);
        match17.simulator();
        MatchSim match18 = new MatchSim(eyupspor, besiktas);
        match18.simulator();
        MatchSim match19 = new MatchSim(besiktas, trabzonspor);
        match19.simulator();
        MatchSim match20 = new MatchSim(trabzonspor, besiktas);
        match20.simulator();
        MatchSim match21 = new MatchSim(besiktas, basaksehir);
        match21.simulator();
        MatchSim match22 = new MatchSim(basaksehir, besiktas);
        match22.simulator();
        MatchSim match23 = new MatchSim(fenerbahce, sivasspor);
        match23.simulator();
        MatchSim match24 = new MatchSim(sivasspor, fenerbahce);
        match24.simulator();
        MatchSim match25 = new MatchSim(fenerbahce, eyupspor);
        match25.simulator();
        MatchSim match26 = new MatchSim(eyupspor, fenerbahce);
        match26.simulator();
        MatchSim match27 = new MatchSim(fenerbahce, trabzonspor);
        match27.simulator();
        MatchSim match28 = new MatchSim(trabzonspor, fenerbahce);
        match28.simulator();
        MatchSim match29 = new MatchSim(fenerbahce, basaksehir);
        match29.simulator();
        MatchSim match30 = new MatchSim(basaksehir, fenerbahce);
        match30.simulator();
        MatchSim match31 = new MatchSim(sivasspor, eyupspor);
        match31.simulator();
        MatchSim match32 = new MatchSim(eyupspor, sivasspor);
        match32.simulator();
        MatchSim match33 = new MatchSim(sivasspor, trabzonspor);
        match33.simulator();
        MatchSim match34 = new MatchSim(trabzonspor, sivasspor);
        match34.simulator();
        MatchSim match35 = new MatchSim(sivasspor, basaksehir);
        match35.simulator();
        MatchSim match36 = new MatchSim(basaksehir, sivasspor);
        match36.simulator();
        MatchSim match37 = new MatchSim(eyupspor, trabzonspor);
        match37.simulator();
        MatchSim match38 = new MatchSim(trabzonspor, eyupspor);
        match38.simulator();
        MatchSim match39 = new MatchSim(eyupspor, basaksehir);
        match39.simulator();
        MatchSim match40 = new MatchSim(basaksehir, eyupspor);
        match40.simulator();
        MatchSim match41 = new MatchSim(trabzonspor, basaksehir);
        match41.simulator();
        MatchSim match42 = new MatchSim(basaksehir, trabzonspor);
        match42.simulator();
        //All matches and results.
        System.out.println("All matches and results :  ");
        MatchResults results=new MatchResults(42);
        results.push(match1.getResult());
        results.push(match2.getResult());
        results.push(match3.getResult());
        results.push(match4.getResult());
        results.push(match5.getResult());
        results.push(match6.getResult());
        results.push(match7.getResult());
        results.push(match8.getResult());
        results.push(match9.getResult());
        results.push(match10.getResult());
        results.push(match11.getResult());
        results.push(match12.getResult());
        results.push(match13.getResult());
        results.push(match14.getResult());
        results.push(match15.getResult());
        results.push(match16.getResult());
        results.push(match17.getResult());
        results.push(match18.getResult());
        results.push(match19.getResult());
        results.push(match20.getResult());
        results.push(match21.getResult());
        results.push(match22.getResult());
        results.push(match23.getResult());
        results.push(match24.getResult());
        results.push(match25.getResult());
        results.push(match26.getResult());
        results.push(match27.getResult());
        results.push(match28.getResult());
        results.push(match29.getResult());
        results.push(match30.getResult());
        results.push(match31.getResult());
        results.push(match32.getResult());
        results.push(match33.getResult());
        results.push(match34.getResult());
        results.push(match35.getResult());
        results.push(match36.getResult());
        results.push(match37.getResult());
        results.push(match38.getResult());
        results.push(match39.getResult());
        results.push(match40.getResult());
        results.push(match41.getResult());
        results.push(match42.getResult());
        //Now time to show.
        results.printStack();
        System.out.println(" ");
        //Show league ranks.
        LeagueRanks league = new LeagueRanks(7);
        league.addTeamToRanking(besiktas);
        league.addTeamToRanking(fenerbahce);
        league.addTeamToRanking(galatasaray);
        league.addTeamToRanking(eyupspor);
        league.addTeamToRanking(basaksehir);
        league.addTeamToRanking(trabzonspor);
        league.addTeamToRanking(sivasspor);
        league.printStandings();
        System.out.println(" ");
        //Print champion!
        System.out.println("CHAMPION IS "+league.teams[0].teamName.toUpperCase());
     
        
        
    }
    
}
